# Generated by Django 4.1.7 on 2024-02-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('lob', models.CharField(max_length=100)),
                ('creative_type', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('file_object_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
